#AWS CodeDeploy 설정
version: 0.0  #CodeDeploy의 버전
os: linux
files:
  - source: / #CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정(/: 전체 파일)
#    destination: /home/ec2-user/app/step3/zip/  #source에서 지정된 파일을 받을 위치
    destination: /home/ec2-user/zerock/zip/  #source에서 지정된 파일을 받을 위치
    orverwrite: yes

permissions: #CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 설정
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
#    type: #권한 설정할 타입 지정
#      - file

hooks:  #CodeDeploy 배포 단계에서 실행할 명령어를 지정
#  AfterInstall:
#    - location: stop.sh #nginx와 연결되어 있지 않은 스프링 부트를 종료
#    - location: stop_docker.sh #nginx와 연결되어 있지 않은 스프링 부트를 종료
#      timeout: 60
#      runas: ec2-user
  ApplicationStart: #ApplicationStart라는 단계에서 deploy.sh을 ec2-user 권한으로 실행
#    - location: deploy.sh  #무중단 배포 AS-IS
#    - location: start.sh  #TO-BE
    - location: deploy_zerock.sh
      timeout: 60 #스크립트 실행 60초 이상 수행되면 실패
      runas: ec2-user
#  ValidateService:
##    - location: health.sh #새 스프링 부트가 정상적으로 실행됐는지 확인
#    - location: health_docker.sh #새 스프링 부트가 정상적으로 실행됐는지 확인
#      timeout: 60
#      runas: ec2-user