spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  profiles:
    group:
      local: local, local-db
      real: real, real-db

  mvc:
    hiddenmethod:
      filter:
        enabled: true #html form tag에서 PATH, DELETE 등의 method 사용이 불가한 문제 해결을 위한 filter 적용
