server:
  port: 8080

spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update  #프로젝트 실행 시 자동으로 DDL을 생성할 것인지 설정(create, update, create-drop, validate)

    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: true