spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  profiles:
    group:
      test: test, test-db
      local: local, local-db
      real: real-db
