server:
  port: 8080

spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update  #프로젝트 실행 시 자동으로 DDL을 생성할 것인지 설정(create, update, create-drop, validate)

    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: true

#파일 업로드 설정
  servlet:
    multipart:
      enabled: true #파일 업로드 가능 여부 선택
      location: /home/ec2-user/zerock/upload/  #업로드된 파일의 임시 저장 경로
      max-request-size: 30MB  #한 번에 최대 업로드 가능 용량
      max-file-size: 10MB #파일 하나의 최대 크기

#피일 업로드 경로
com:
  jongtix:
    zerock:
      upload:
        path: /home/ec2-user/zerock/upload/

logging:
  level:
    org:
      zerock:
        security: debug